name: compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    uses: oe-alliance-plugins/.github/.github/workflows/compile.yml@main
    # with:
    #   path: src
    #   python-versions: '["3.14"]'
