name: Pylint Code Check

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    uses: openatv/.github/.github/workflows/pylint.yml@main
    # with:
    #   path: src
